// Generated by CoffeeScript 1.4.0
(function() {
  var codeInput, gutter, resultsPanel, updateSheet;

  codeInput = document.getElementById('code-input');

  resultsPanel = document.getElementById('results-panel');

  gutter = document.getElementById('gutter');

  updateSheet = function() {
    var code, evaluator, gutterHtmls, i, line, lines, result, resultHtmls, varname, _i, _len;
    lines = codeInput.value.split('\n');
    evaluator = new TapDigit.Evaluator();
    resultHtmls = [];
    gutterHtmls = [];
    i = 0;
    for (i = _i = 0, _len = lines.length; _i < _len; i = ++_i) {
      line = lines[i];
      varname = 'L' + (i + 1);
      code = varname + ' = ' + line;
      result = line ? evaluator.evaluate(code) : '-';
      resultHtmls.splice(resultHtmls.length, 0, '<div class=result data-label="', varname, ': ">', result, '</div>');
      gutterHtmls.splice(gutterHtmls.length, 0, '<div>', varname, ': ', '</div>');
    }
    resultsPanel.innerHTML = resultHtmls.join('');
    return gutter.innerHTML = gutterHtmls.join('');
  };

  codeInput.addEventListener('keydown', function() {
    return setTimeout(updateSheet, 0);
  });

  codeInput.addEventListener('change', updateSheet);

  codeInput.value = ['a = 2', 'a', 'sin(pi/4) * sqrt(a) + 42', 'L3'].join('\n');

  updateSheet();

}).call(this);
